spring:
  application:
    name: gatling-service
  datasource:
    host: localhost
    port: 27017
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
            
server:
  port: 8090