{
 "title": "Applications Metrics Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "App Request Count",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "customer_request_counter_total ",
     "legendFormat": "App request count"
    }
   ]
  },
  {
   "title": "Good App Response Status - Success",
   "type": "graph",
   "gridPos": { "h": 4, "w": 5, "x": 3, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "customer_counter_status_200_total",
     "legendFormat": "customer response status- Success"
    }
   ]
  },
  {
   "title": "Bad App Response Status - Success",
   "type": "graph",
   "gridPos": { "h": 4, "w": 5, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "product_counter_status_200_total",
     "legendFormat": "Bad App response status - Success"
    }
   ]
  },
  {
   "title": "Good App Response Time - Success",
   "type": "graph",
   "gridPos": { "h": 4, "w": 5, "x": 13, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "Customer_seconds_sum{status=\"200\"}",
     "legendFormat": "Good App response time - success"
    }
   ]
  },
  {
   "title": "Bad App Response Time - Success",
   "type": "graph",
   "gridPos": { "h": 4, "w": 5, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(Product_seconds_sum{status=\"200\"}) ",
     "legendFormat": "product response time - Success"
    }
   ]
  },
  {
   "title": "Chaos Monkey Assaults",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "chaos_monkey_application_request_count_total{type=\"assaulted\"}",
     "legendFormat": "assaulted request count"
    }
   ]
  },
  {
   "title": "Good App Response Status - Failure ",
   "type": "graph",
   "gridPos": { "h": 4, "w": 5, "x": 3, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "customer_counter_status_500_total",
     "legendFormat": "Good App response status - Success"
    },
    {
     "expr": "customer_counter_status_500_total",
     "legendFormat": "customer response status - Failure"
    }
   ]
  },
  {
   "title": "Bad App Response Status - Failure",
   "type": "graph",
   "gridPos": { "h": 4, "w": 5, "x": 8, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "product_counter_status_500_total",
     "legendFormat": "Bad App response status - Failure"
    }
   ]
  },
  {
   "title": "Good App Response Time - Failure",
   "type": "graph",
   "gridPos": { "h": 4, "w": 5, "x": 13, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "Customer_seconds_sum{status=\"500\"}",
     "legendFormat": "Good App response time - failure"
    }
   ]
  },
  {
   "title": "Bad App Response Time - Failure",
   "type": "graph",
   "gridPos": { "h": 4, "w": 5, "x": 18, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(Product_seconds_sum{status=\"500\"}) ",
     "legendFormat": "product response time - Failure"
    }
   ]
  },
  {
   "title": "Good App JVM Thread",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 3, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_states_threads{application=\"chaos-demo-customer\", state=\"runnable\"}",
     "legendFormat": "Runnable Threads"
    },
    {
     "expr": "jvm_threads_states_threads{application=\"chaos-demo-customer\", state=\"waiting\"}",
     "legendFormat": "Waiting Threads"
    },
    {
     "expr": "jvm_threads_states_threads{application=\"chaos-demo-customer\", state=\"timed-waiting\"}",
     "legendFormat": "Timed Waiting Threads"
    },
    {
     "expr": "jvm_threads_states_threads{application=\"chaos-demo-customer\", state=\"blocked\"}",
     "legendFormat": "Blocked Threads"
    }
   ]
  },
  {
   "title": "Bad App JVM Memory",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 13, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{application=\"chaos-demo-product\", id=\"PS Old Gen\"}",
     "legendFormat": "Used Old Gen"
    },
    {
     "expr": "jvm_memory_used_bytes{application=\"chaos-demo-product\", id=\"PS Survivor Space\"}",
     "legendFormat": "Used Survivor Space"
    }
   ]
  },
  {
   "title": "Good App JVM Memory",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 3, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{application=\"chaos-demo-customer\", id=\"PS Old Gen\"}",
     "legendFormat": "Used Old Gen"
    },
    {
     "expr": "jvm_memory_used_bytes{application=\"chaos-demo-customer\", id=\"PS Survivor Space\"}",
     "legendFormat": "Used Survivor Space"
    }
   ]
  },
  {
   "title": "Bad App JVM Thread",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 13, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_states_threads{application=\"chaos-demo-product\", state=\"runnable\"}",
     "legendFormat": "Runnable Threads"
    },
    {
     "expr": "jvm_threads_states_threads{application=\"chaos-demo-product\", state=\"waiting\"}",
     "legendFormat": "Waiting Threads"
    },
    {
     "expr": "jvm_threads_states_threads{application=\"chaos-demo-product\", state=\"timed-waiting\"}",
     "legendFormat": "Timed Waiting Threads"
    },
    {
     "expr": "jvm_threads_states_threads{application=\"chaos-demo-product\", state=\"blocked\"}",
     "legendFormat": "Blocked Threads"
    }
   ]
  }
 ]
}