{
 "title": "VPT Demo using stubs and Latency Injection",
 "time": { "from": "now-1m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "App Request Count",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 8, "x": 2, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "customer_request_counter_total", "legendFormat": "App request count" }
   ]
  },
  {
   "title": "Chaos Latency Assaults",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 11, "x": 10, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "chaos_monkey_application_request_count_total{application=\"chaos-demo-ods-simulation\",type=\"assaulted\"}",
     "legendFormat": "assaulted request count"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 10, "x": 0, "y": 2 },
   "content": "<center><DIV><font size=\"7\">     NON-RESILIENT APP     </font></DIV>\n\n\n\n"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 10, "x": 13, "y": 2 },
   "content": "\n<center><div><font size=\"7\">     RESILIENT APP     </font></div>\n\n\n\n"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 4 },
   "content": "\n<center><DIV> <font size=\"5\">    Customer Impact    </font></DIV>\n\n\n\n"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 4 },
   "content": "\n<center><DIV><font size=\"5\">     Response Time     </font></DIV>\n\n\n\n"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 4 },
   "content": "\n<center><DIV><font size=\"5\">     Customer Impact     </font></DIV>\n\n\n\n"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 4 },
   "content": "\n<center><DIV><font size=\"5\">     Response Time     </font></DIV>\n\n\n\n"
  },
  {
   "title": "Success",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate (product_counter_status_200_total[30s])",
     "legendFormat": "Non Stubbed App response status - Success"
    }
   ]
  },
  {
   "title": "Success",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(Product_seconds_sum{status=\"200\"}[30s])",
     "legendFormat": "Non Stubbed App response time - Success"
    }
   ]
  },
  {
   "title": "Success",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(customer_counter_status_200_total[30s])",
     "legendFormat": "Stubbed App response status- Success"
    }
   ]
  },
  {
   "title": "Success",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(Customer_seconds_sum{status=\"200\"}[30s])",
     "legendFormat": "Stubbed App response time - success"
    }
   ]
  },
  {
   "title": "Failure",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(product_counter_status_500_total[30s])",
     "legendFormat": "Non Stubbed App response status - Failure"
    }
   ]
  },
  {
   "title": "Failure",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(Product_seconds_sum{status=\"500\"}[30s]) ",
     "legendFormat": "Non Stubbed App response time - Failure"
    }
   ]
  },
  {
   "title": "Failures",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(customer_counter_status_500_total[30s])",
     "legendFormat": "Stubbed App response status - Success"
    }
   ]
  },
  {
   "title": "Failures",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(Customer_seconds_sum{status=\"500\"}[30s])",
     "legendFormat": "Stubbed App response time - failure"
    }
   ]
  },
  {
   "title": "JVM Thread State",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_states_threads{application=\"chaos-demo-customer\", state=\"timed-waiting\"}",
     "legendFormat": "Timed Waiting"
    },
    {
     "expr": "jvm_threads_states_threads{application=\"chaos-demo-customer\", state=\"runnable\"}",
     "legendFormat": "Runnable"
    }
   ]
  },
  {
   "title": "JVM Thread State",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_states_threads{application=\"chaos-demo-product\", state=\"timed-waiting\"}",
     "legendFormat": "Timed Waiting"
    },
    {
     "expr": "jvm_threads_states_threads{application=\"chaos-demo-product\", state=\"runnable\"}",
     "legendFormat": "Runnable"
    }
   ]
  }
 ]
}