spring:
  application:
    name: ods-simulation-service
  datasource:
    host: localhost
    port: 27018
  profiles:
    active: chaos-monkey
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
server:
  port: 8094

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

chaos:
  monkey:
    enabled: true
    assaults:
      level: 1
      latencyRangeStart: 2000
      latencyRangeEnd: 5000
      exceptionsActive: false
      killApplicationActive: false
      proxyTargetClass: false
    watcher:
      repository: true
      restController: true

management:
  endpoint:
    chaosmonkey:
      enabled: true
    metrics:
      enabled: true
    prometheus:
      enabled: true
    chaosmonkeyjmx:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    export:
      prometheus:
        enabled: true
