spring:
  application:
    name: gateway-service
      
server:
  port: 8090

eureka:
  client:
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
ribbon:
  ConnectTimeout: 50000
  ReadTimeout: 50000
  
hystrix:
  command:
    default:
      execution:
        isolation: 
          thread:
            timeoutInMilliseconds: 15000
      fallback:
        enabled: false
      circuitBreaker:
        enabled: false