spring:
  application:
    name: order-service
  datasource:
    host: localhost
    port: 27017
  profiles:
    active: chaos-monkey
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
server:
  port: 8091

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    de.codecentric: TRACE

feign:
  client:
    config:
      default:
        connectTimeout: 2000
        readTimeout: 2000
        loggerLevel: basic
  hystrix:
    enabled: true

ribbon:
  ConnectTimeout: 2000
  ReadTimeout: 2000
                   
chaos:
  monkey:
    enabled: false
    assaults:
      level: 8
      latencyRangeStart: 1000
      latencyRangeEnd: 10000
      exceptionsActive: false
      killApplicationActive: false
    watcher:
      repository: true
      
management:
  endpoint:
    chaosmonkey:
      enabled: true
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    export:
      prometheus:
        enabled: true