spring:
  application:
    name: product-service
  datasource:
    host: localhost
    port: 27017
  profiles:
    active: chaos-monkey
server:
  port: 8092

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
chaos:
  monkey:
    enabled: false
    assaults:
      level: 7
      latencyRangeStart: 1000
      latencyRangeEnd: 10000
      exceptionsActive: false
      killApplicationActive: false
    watcher:
      repository: true
      restController: true
      
management:
  endpoint:
    chaosmonkey:
      enabled: true
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,chaosmonkey
  metrics:
    export:
      prometheus:
        enabled: true